-- Mrkoon PMS — Real KPIs Import v1
-- Date: 2026-05-06
-- Source: okr-kpi-framework-v6-20260502.xlsx, sheet "KPI Master"

-- Step 1: Wipe placeholder KPIs (KPI-001..KPI-040)
delete from def.kpi_role_weights where kpi_id like 'KPI-%';
delete from def.kpis where id like 'KPI-%';

-- Step 2: Insert real KPIs
insert into def.kpis (id, name_en, name_ar, formula_text, frequency, target_value, weight_default, weight_type_default, kr_ref) values
  ('BD-01', 'Lead First-Contact Time', 'وقت التواصل الأول مع العميل المحتمل', 'Time from lead assignment to first outbound call', 'monthly', 24.0, 0.15, 'scored', (select id from def.key_results where code='CO1.KR4')),
  ('BD-02', 'Weekly Outbound Calls', 'المكالمات الصادرة الأسبوعية', 'Count of outbound prospecting + follow-up calls', 'weekly', 30.0, 0.1, 'scored', (select id from def.key_results where code='CO1.KR3')),
  ('BD-03', 'Meeting Conversion Rate', 'معدل تحويل الاجتماعات', 'Meetings booked / leads contacted', 'monthly', 0.5, 0.15, 'scored', (select id from def.key_results where code='CO1.KR3')),
  ('BD-04', 'Deal Close Rate', 'معدل إغلاق الصفقات', 'Signed contracts / meetings held', 'monthly', 0.3, 0.2, 'scored', (select id from def.key_results where code='CO1.KR3')),
  ('BD-05', 'First-Month Client Activation', 'تفعيل العميل في الشهر الأول', 'New clients with >= 1 auction in first 30 days / total new', 'monthly', 1.0, 0.2, 'scored', (select id from def.key_results where code='CO1.KR3')),
  ('BD-06', 'Client Handoff to AM', 'تسليم العميل لمدير الحسابات', 'Clients handed to AM with complete file / total activated clients', 'monthly', 1.0, 0.1, 'scored', (select id from def.key_results where code='CO2.KR1')),
  ('BD-07', 'Pipeline Value', 'قيمة خط المبيعات', 'Sum of estimated deal values in active pipeline', 'monthly', 5.0, 0.1, 'scored', (select id from def.key_results where code='CO1.KR1')),
  ('AM-01', 'Client Retention Rate (MoM)', 'معدل الاحتفاظ بالعملاء (شهري)', 'Clients with >= 1 txn this month / clients active last month', 'monthly', 0.85, 0.2, 'scored', (select id from def.key_results where code='CO2.KR1')),
  ('AM-02', 'Client Reactivation Rate', 'معدل إعادة تفعيل العملاء', 'Re-engaged clients (txn after 30+ day gap) / total churned list', 'quarterly', 0.2, 0.15, 'scored', (select id from def.key_results where code='CO2.KR2')),
  ('AM-03', 'Average Transactions per Client', 'متوسط المعاملات لكل عميل', 'Total txns from managed portfolio / active client count', 'monthly', 2.0, 0.15, 'scored', (select id from def.key_results where code='CO2.KR3')),
  ('AM-04', 'Upselling — New Scrap Categories', 'البيع الإضافي — فئات خردة جديدة', 'New category auctions from existing clients in portfolio', 'quarterly', 2.0, 0.1, 'scored', (select id from def.key_results where code='CO2.KR4')),
  ('AM-05', 'Client Referrals Generated', 'إحالات العملاء المحققة', 'New clients who cite existing client as referral source', 'quarterly', 1.0, 0.1, 'scored', (select id from def.key_results where code='CO2.KR4')),
  ('AM-06', 'Client Satisfaction / Issue Resolution', 'رضا العميل / حل المشكلات', 'Issues acknowledged within 4 hrs / total issues raised', 'monthly', 1.0, 0.1, 'scored', (select id from def.key_results where code='CO2.KR1')),
  ('AM-07', 'Auction Coordination with Client', 'تنسيق المزاد مع العميل', 'On-time announcements / total auctions for managed clients', 'monthly', 1.0, 0.1, 'scored', (select id from def.key_results where code='CO2.KR3')),
  ('AM-08', 'Post-Auction Client Report', 'تقرير ما بعد المزاد للعميل', 'On-time reports / total auctions for managed clients', 'monthly', 1.0, 0.1, 'scored', (select id from def.key_results where code='CO2.KR3')),
  ('OPS-TL-01', 'Personal: Quality Bonus (zero-issue)', 'شخصي: مكافأة الجودة (صفر مشاكل)', 'Personal loading issues / personal total loadings', 'monthly', NULL, 0.3, 'scored', (select id from def.key_results where code='CO4.KR3')),
  ('OPS-TL-02', 'Personal: Volume — Loadings Completed', 'شخصي: الحجم — عمليات التحميل المنجزة', 'Count of loadings personally supervised', 'monthly', 10.0, 0.3, 'scored', (select id from def.key_results where code='CO1.KR2')),
  ('OPS-TL-03', 'Personal: Client Referral/Upsell Support', 'شخصي: دعم إحالات/بيع إضافي للعملاء', 'Referred clients who sign / month', 'monthly', 1.0, 0.2, 'scored', (select id from def.key_results where code='CO2.KR4')),
  ('OPS-TL-04', 'Daily Activity Report', 'تقرير النشاط اليومي', 'On-time reports / working days', 'daily', 1.0, 0.2, 'scored', NULL),
  ('OPS-GATE-01', 'OPS GATE 1: Zero-Issue Loading Rate', 'بوابة العمليات 1: معدل التحميل بدون مشاكل', 'Team zero-issue loadings / team total loadings', 'monthly', 0.95, NULL, 'gate', (select id from def.key_results where code='CO4.KR3')),
  ('OPS-GATE-02', 'OPS GATE 2: Loading Speed', 'بوابة العمليات 2: سرعة التحميل', 'On-time loadings / total scheduled loadings', 'monthly', 0.9, NULL, 'gate', (select id from def.key_results where code='CO4.KR5')),
  ('OPS-GATE-03', 'OPS GATE 3: Report Compliance', 'بوابة العمليات 3: التزام التقارير', 'On-time team reports / total required reports', 'monthly', 1.0, NULL, 'gate', NULL),
  ('OPS-GATE-04', 'VM GATE 1: Merchant Coverage', 'بوابة إدارة البائعين 1: تغطية التجار', 'Qualifying auctions / total auctions', 'monthly', 0.8, NULL, 'gate', (select id from def.key_results where code='CO3.KR2')),
  ('OPS-GATE-05', 'VM GATE 2: Auction Price Quality', 'بوابة إدارة البائعين 2: جودة سعر المزاد', 'Auctions meeting 125% rule / total auctions', 'monthly', 0.8, NULL, 'gate', (select id from def.key_results where code='CO1.KR4')),
  ('OPS-BIZ-01', 'Item Onboarding Time', 'وقت إدراج الأصناف', 'Avg days from item receipt to platform listing', 'monthly', 3.0, 0.2, 'scored', (select id from def.key_results where code='CO6.KR1')),
  ('OPS-BIZ-02', 'Item Data Completeness', 'اكتمال بيانات الأصناف', 'Fully complete item listings / total items onboarded', 'monthly', 1.0, 0.15, 'scored', (select id from def.key_results where code='CO6.KR1')),
  ('OPS-BIZ-03', 'Price Collection Accuracy', 'دقة تحصيل الأسعار', 'Items with collected price within 10% of market reference / total', 'monthly', 0.95, 0.2, 'scored', (select id from def.key_results where code='CO6.KR2')),
  ('OPS-BIZ-04', 'Starting Auction Price Negotiation', 'التفاوض على سعر بدء المزاد', 'Negotiations closed within 2 rounds / total negotiations', 'monthly', 0.9, 0.15, 'scored', (select id from def.key_results where code='CO6.KR2')),
  ('OPS-BIZ-05', 'Term Sheet Preparation', 'إعداد كشف الشروط', 'Auctions with approved term sheet / total launched', 'monthly', 1.0, 0.2, 'scored', (select id from def.key_results where code='CO6.KR3')),
  ('OPS-BIZ-06', 'Term Sheet Accuracy', 'دقة كشف الشروط', 'Term sheets requiring correction / total term sheets', 'monthly', 0.02, 0.1, 'scored', (select id from def.key_results where code='CO6.KR3')),
  ('OPS-FIELD-01', 'Time from Signing to First Visit', 'الوقت من التوقيع إلى أول زيارة', 'Hours between contract sign and first visit', 'monthly', 48.0, 0.15, 'scored', (select id from def.key_results where code='CO4.KR1')),
  ('OPS-FIELD-02', 'Client Data Accuracy (12 Fields)', 'دقة بيانات العميل (12 حقل)', 'Clients with all 12 fields valid / total handled', 'monthly', 1.0, 0.1, 'scored', (select id from def.key_results where code='CO4.KR1')),
  ('OPS-FIELD-03', 'Inspection Completion Rate', 'معدل إتمام المعاينة', 'On-time inspections / total scheduled', 'weekly', 0.95, 0.15, 'scored', (select id from def.key_results where code='CO4.KR2')),
  ('OPS-FIELD-04', 'Loading Execution — Zero Issue', 'تنفيذ التحميل — صفر مشاكل', 'Loadings without issues / total loadings', 'monthly', 0.95, 0.2, 'scored', (select id from def.key_results where code='CO4.KR3')),
  ('OPS-FIELD-05', 'Loading Speed — Within 48hrs', 'سرعة التحميل — خلال 48 ساعة', 'On-time loadings / total scheduled loadings', 'monthly', 0.9, 0.15, 'scored', (select id from def.key_results where code='CO4.KR5')),
  ('OPS-FIELD-06', 'Agreement Stability', 'استقرار الاتفاقيات', 'Unchanged agreements / total post-inspection', 'monthly', 0.9, 0.1, 'scored', (select id from def.key_results where code='CO4.KR2')),
  ('OPS-FIELD-07', 'Daily Activity Report', 'تقرير النشاط اليومي', 'On-time reports / working days', 'daily', 1.0, 0.1, 'scored', NULL),
  ('OPS-FIELD-08', 'Volume — Loadings per Month', 'الحجم — عمليات التحميل الشهرية', 'Count of completed loadings per month', 'monthly', 1.0, 0.05, 'scored', (select id from def.key_results where code='CO1.KR2')),
  ('VM-01', 'Merchant Calls per Auction', 'مكالمات التجار لكل مزاد', 'Outbound calls per auction / auction count', 'monthly', 25.0, 0.08, 'scored', (select id from def.key_results where code='CO3.KR2')),
  ('VM-02', 'Auction Success Rate (125% Rule)', 'معدل نجاح المزاد (قاعدة 125%)', 'Auctions where final bid >= reserve price × 1.25 / total auctions.', 'weekly', 0.8, 0.16, 'scored', (select id from def.key_results where code='CO1.KR4')),
  ('VM-03', 'Paid Insurance Merchants per Auction', 'التجار المؤمنون لكل مزاد', 'Merchants with paid insurance at auction launch', 'monthly', 6.0, 0.12, 'scored', (select id from def.key_results where code='CO3.KR2')),
  ('VM-04', 'Active Bidders per Auction', 'المزايدون النشطون لكل مزاد', 'Merchants who place >= 1 bid per auction', 'monthly', 3.0, 0.08, 'scored', (select id from def.key_results where code='CO3.KR2')),
  ('VM-05', 'New Merchants per Auction', 'التجار الجدد لكل مزاد', 'First-time auction participants / auction', 'monthly', 2.0, 0.08, 'scored', (select id from def.key_results where code='CO3.KR4')),
  ('VM-06', 'Merchant Follow-up After Auction', 'متابعة التاجر بعد المزاد', 'Merchants contacted post-auction with results + feedback / total merchants in auction', 'monthly', 1.0, 0.08, 'scored', (select id from def.key_results where code='CO3.KR2')),
  ('VM-07', 'Insurance Collection Timeliness', 'التزام تحصيل التأمين', 'On-time collections / total insurance payments', 'monthly', 1.0, 0.12, 'scored', (select id from def.key_results where code='CO3.KR2')),
  ('VM-08', 'Auction 125% Rule Compliance', 'التزام قاعدة 125% في المزاد', 'Auctions with 125% compliance check / total', 'monthly', 1.0, 0.08, 'scored', (select id from def.key_results where code='CO1.KR4')),
  ('VM-09', 'Per-VM Auction Quality', 'جودة المزاد لكل مندوب VM', 'Confirmed bidders with paid insurance per auction per VM', 'monthly', 6.0, 0.1, 'scored', (select id from def.key_results where code='CO3.KR2')),
  ('VM-10', 'Merchant DB Activation Rate', 'معدل تفعيل قاعدة التجار', 'Active merchants (≥1 auction) / total assigned merchants in DB', 'quarterly', 0.1, 0.1, 'scored', (select id from def.key_results where code='CO3.KR4')),
  ('ONB-01', 'Onboarding Completion Rate', 'معدل إتمام تأهيل التجار', 'Fully onboarded merchants / total started', 'monthly', 0.9, 0.2, 'scored', (select id from def.key_results where code='CO3.KR1')),
  ('ONB-02', 'Merchant Activation Time', 'وقت تفعيل التاجر', 'Avg business days first contact to verification', 'monthly', 5.0, 0.2, 'scored', (select id from def.key_results where code='CO3.KR1')),
  ('ONB-03', 'Document Collection Rate', 'معدل تحصيل المستندات', 'Merchants with complete docs / total activated', 'monthly', 1.0, 0.2, 'scored', (select id from def.key_results where code='CO3.KR1')),
  ('ONB-04', 'Merchant Data Quality', 'جودة بيانات التجار', 'Clean records / total records audited', 'monthly', 0.98, 0.2, 'scored', (select id from def.key_results where code='CO3.KR1')),
  ('ONB-05', 'Merchant Database Cleaning', 'تنظيف قاعدة بيانات التجار', 'Verified + updated merchant records per category', 'monthly', 50.0, 0.2, 'scored', (select id from def.key_results where code='CO3.KR1')),
  ('MKT-TL-01', 'Client Lead Volume (LinkedIn)', 'حجم العملاء المحتملين (لينكدإن)', 'LinkedIn campaign lead count (Egypt)', 'monthly', 40.0, 0.15, 'scored', (select id from def.key_results where code='CO5.KR1')),
  ('MKT-TL-02', 'Client CPL (LinkedIn)', 'تكلفة العميل المحتمل (لينكدإن)', 'Total LinkedIn client spend / qualified leads', 'monthly', 700.0, 0.15, 'scored', (select id from def.key_results where code='CO5.KR2')),
  ('MKT-TL-03', 'Merchant Lead Volume (Meta)', 'حجم التجار المحتملين (ميتا)', 'Meta campaign leads passing trust verification', 'monthly', 100.0, 0.1, 'scored', (select id from def.key_results where code='CO3.KR3')),
  ('MKT-TL-04', 'Merchant CPL (Meta)', 'تكلفة التاجر المحتمل (ميتا)', 'Total Meta merchant spend / trusted leads', 'monthly', 100.0, 0.1, 'scored', (select id from def.key_results where code='CO3.KR3')),
  ('MKT-TL-05', 'Lead-to-Meeting Conversion Rate', 'معدل تحويل العملاء المحتملين لاجتماعات', 'Leads that became BD meetings / total marketing leads', 'monthly', 0.3, 0.1, 'scored', (select id from def.key_results where code='CO1.KR3')),
  ('MKT-TL-06', 'Campaign ROI Report', 'تقرير عائد الحملات', 'On-time report delivery (yes/no per month)', 'monthly', 3.0, 0.05, 'scored', NULL),
  ('MKT-TL-07', 'Team Content Output', 'مخرجات محتوى الفريق', 'Combined team output vs target', 'monthly', 3.0, 0.15, 'scored', (select id from def.key_results where code='CO5.KR4')),
  ('MKT-TL-08', 'Team Campaign ROAS', 'عائد إنفاق الحملات للفريق', 'Revenue attributed to marketing / total ad spend', 'quarterly', 3.0, 0.1, 'scored', (select id from def.key_results where code='CO5.KR1')),
  ('MKT-TL-09', 'Team Turnaround on Requests', 'سرعة تنفيذ طلبات الفريق', 'On-time delivered requests / total requests', 'monthly', 3.0, 0.1, 'scored', NULL),
  ('MKT-SM-01', 'LinkedIn Posts Published', 'منشورات لينكدإن المنشورة', 'Count of published LinkedIn posts', 'monthly', 10.0, 0.25, 'scored', (select id from def.key_results where code='CO5.KR4')),
  ('MKT-SM-02', 'LinkedIn Engagement Rate', 'معدل التفاعل على لينكدإن', '(Likes+comments+shares) / impressions per post', 'monthly', 0.03, 0.25, 'scored', (select id from def.key_results where code='CO5.KR4')),
  ('MKT-SM-03', 'Social Media Follower Growth', 'نمو متابعي وسائل التواصل', '(End followers - start) / start followers', 'quarterly', 0.1, 0.25, 'scored', (select id from def.key_results where code='CO5.KR4')),
  ('MKT-SM-04', 'Content Calendar Adherence', 'الالتزام بجدول المحتوى', 'On-time posts / total planned posts', 'monthly', 0.9, 0.25, 'scored', NULL),
  ('MKT-GD-01', 'Design Deliverables Completed', 'التصميمات المنجزة', 'Count of approved design assets', 'monthly', 20.0, 0.3, 'scored', (select id from def.key_results where code='CO5.KR4')),
  ('MKT-GD-02', 'Design Turnaround Time', 'وقت تسليم التصميم', 'Avg business days request to delivered', 'monthly', 2.0, 0.3, 'scored', NULL),
  ('MKT-GD-03', 'Revision Rate', 'معدل التعديلات', 'Total revision rounds / total deliverables', 'monthly', 1.0, 0.2, 'scored', NULL),
  ('MKT-GD-04', 'Brand Consistency Score', 'درجة تناسق الهوية البصرية', 'Assets passing brand check / total', 'monthly', 0.95, 0.2, 'scored', NULL),
  ('MKT-CC-01', 'Video Content Produced', 'محتوى الفيديو المنتج', 'Count of published/delivered videos', 'monthly', 3.0, 0.2, 'scored', (select id from def.key_results where code='CO5.KR4')),
  ('MKT-CC-02', 'Motion Picture / Premium Video', 'فيديو سينمائي / فيديو احترافي', 'Delivered motion picture / quarterly target', 'quarterly', 1.0, 0.15, 'scored', (select id from def.key_results where code='CO5.KR4')),
  ('MKT-CC-03', 'Written Content Pieces', 'قطع المحتوى المكتوب', 'Count of approved written content', 'monthly', 8.0, 0.15, 'scored', (select id from def.key_results where code='CO5.KR4')),
  ('MKT-CC-04', 'Content Ideas Generation', 'توليد أفكار المحتوى', 'Ideas submitted per week (from Nadeem OKR)', 'weekly', 2.0, 0.15, 'scored', NULL),
  ('MKT-CC-05', 'Content Turnaround Time', 'وقت تسليم المحتوى', 'Avg days from brief to delivery', 'monthly', 3.0, 0.15, 'scored', NULL),
  ('MKT-CC-06', 'Content Engagement Rate', 'معدل التفاعل مع المحتوى', '(Interactions / impressions) on content', 'monthly', 0.02, 0.2, 'scored', (select id from def.key_results where code='CO5.KR4')),
  ('MKT-MOD-01', 'DM/Inquiry Response Time', 'وقت الرد على الرسائل/الاستفسارات', 'Avg minutes from inquiry to first response', 'daily', 1.0, 0.3, 'scored', (select id from def.key_results where code='CO5.KR4')),
  ('MKT-MOD-02', 'Response Rate', 'معدل الرد', 'Same-day responses / total inquiries', 'daily', 0.95, 0.25, 'scored', NULL),
  ('MKT-MOD-03', 'Community Comment Moderation', 'إدارة تعليقات المجتمع', 'On-time moderated / total comments', 'daily', 1.0, 0.25, 'scored', NULL),
  ('MKT-MOD-04', 'Lead Handoff Accuracy', 'دقة تسليم العملاء المحتملين', 'Correctly routed leads / total handled', 'weekly', 0.98, 0.2, 'scored', (select id from def.key_results where code='CO5.KR3')),
  ('TECH-PO-01', 'Product Roadmap Delivery', 'تسليم خارطة المنتج', 'Delivered features / planned features', 'quarterly', 0.85, 0.2, 'scored', NULL),
  ('TECH-PO-02', 'Release Cycle Time', 'وقت دورة الإصدار', 'Avg days sprint start to production', 'monthly', 2.0, 0.2, 'scored', NULL),
  ('TECH-PO-03', 'Sprint Planning Accuracy', 'دقة تخطيط السبرنت', 'Completed story points / committed', 'monthly', 0.8, 0.15, 'scored', NULL),
  ('TECH-PO-04', 'Critical Bug Backlog', 'قائمة الأخطاء الحرجة المتراكمة', 'Count of open P1/P2 bugs', 'weekly', 3.0, 0.15, 'scored', NULL),
  ('TECH-PO-05', 'App Store Rating', 'تقييم متجر التطبيقات', 'Average app store rating', 'monthly', 4.0, 0.1, 'scored', NULL),
  ('TECH-PO-06', 'Stakeholder Feedback Score', 'درجة رضا أصحاب المصلحة', 'Avg score monthly stakeholder survey', 'monthly', 4.0, 0.2, 'scored', NULL),
  ('TECH-PO-07', 'Team Sprint Velocity [MONITORING — not scored]', 'سرعة سبرنت الفريق', 'Team delivered pts / team committed pts', 'monthly', 0.9, NULL, 'monitor', NULL),
  ('TECH-PO-08', 'Team Code Quality [MONITORING — not scored]', 'جودة كود الفريق', 'Avg PR review turnaround across team', 'monthly', 24.0, NULL, 'monitor', NULL),
  ('TECH-PO-09', 'Team Bug Escape Rate [MONITORING — not scored]', 'معدل تسرب الأخطاء للإنتاج', 'Prod bugs / (pre-release + prod bugs)', 'monthly', 0.1, NULL, 'monitor', NULL),
  ('TECH-DEV-01', 'Sprint Velocity (Story Points)', 'سرعة السبرنت (نقاط القصة)', 'Delivered pts / committed pts per sprint', 'monthly', 0.9, 0.25, 'scored', NULL),
  ('TECH-DEV-02', 'Code Review Turnaround', 'وقت مراجعة الكود', 'Avg hours PR submission to review', 'monthly', 24.0, 0.15, 'scored', NULL),
  ('TECH-DEV-03', 'Bug Fix Resolution Time', 'وقت حل الأخطاء', 'Avg resolution time by priority', 'weekly', 1.0, 0.2, 'scored', NULL),
  ('TECH-DEV-04', 'Unit Test Coverage', 'تغطية اختبارات الوحدة', 'Test coverage % on new PRs', 'monthly', 0.7, 0.15, 'scored', NULL),
  ('TECH-DEV-05', 'Deployment Success Rate', 'معدل نجاح النشر', 'Successful deployments / total', 'monthly', 0.95, 0.15, 'scored', NULL),
  ('TECH-DEV-06', 'Documentation Completion', 'إتمام التوثيق', 'Documented features / shipped features', 'monthly', 1.0, 0.1, 'scored', NULL),
  ('TECH-UX-01', 'UI/UX Deliverables', 'مخرجات واجهة/تجربة المستخدم', 'Count of approved screen designs', 'monthly', 10.0, 0.3, 'scored', NULL),
  ('TECH-UX-02', 'Design-to-Dev Handoff Time', 'وقت التسليم من التصميم للتطوير', 'Avg days approval to dev handoff', 'monthly', 1.0, 0.25, 'scored', NULL),
  ('TECH-UX-03', 'Usability Issue Rate', 'معدل مشاكل الاستخدام', 'Post-release usability complaints', 'monthly', 2.0, 0.25, 'scored', NULL),
  ('TECH-UX-04', 'Design System Compliance', 'التزام نظام التصميم', 'Compliant screens / total in audit', 'monthly', 0.95, 0.2, 'scored', NULL),
  ('TECH-QA-01', 'Test Case Execution Rate', 'معدل تنفيذ حالات الاختبار', 'Executed / total planned test cases', 'monthly', 0.95, 0.25, 'scored', NULL),
  ('TECH-QA-02', 'Bug Detection Rate (Pre-Release)', 'معدل اكتشاف الأخطاء (قبل الإصدار)', 'Pre-release bugs / total bugs', 'monthly', 0.9, 0.25, 'scored', NULL),
  ('TECH-QA-03', 'Regression Test Coverage', 'تغطية اختبارات الانحدار', 'Regression tests on critical paths / total', 'monthly', 0.8, 0.25, 'scored', NULL),
  ('TECH-QA-04', 'Test Report Delivery', 'تسليم تقرير الاختبار', 'On-time reports / total sprints', 'monthly', 1.0, 0.25, 'scored', NULL),
  ('FIN-SR-01', 'Invoice Accuracy Rate', 'معدل دقة الفواتير', 'Error-free invoices / total invoices', 'monthly', 0.98, 0.2, 'scored', (select id from def.key_results where code='CO4.KR4')),
  ('FIN-SR-02', 'Insurance Refund Timeliness', 'التزام رد تأمين المزاد', 'Refunds within SLA / total refund requests', 'monthly', 0.9, 0.2, 'scored', NULL),
  ('FIN-SR-03', 'Monthly Reconciliation Timeliness', 'التزام التسوية الشهرية', 'Days after month-end to reconciliation', 'monthly', 3.0, 0.15, 'scored', NULL),
  ('FIN-SR-04', 'Insurance Refund Processing Time', 'وقت معالجة رد التأمين', 'Avg business days refund request to processing', 'monthly', 3.0, 0.15, 'scored', NULL),
  ('FIN-SR-05', 'Commission Revenue Accuracy', 'دقة إيرادات العمولات', 'Verified commission records / total', 'monthly', 1.0, 0.15, 'scored', NULL),
  ('FIN-SR-06', 'Financial Report Delivery', 'تسليم التقرير المالي', 'On-time delivery (yes/no per month)', 'monthly', 3.0, 0.15, 'scored', NULL),
  ('FIN-ACC-01', 'Daily Transaction Recording', 'تسجيل المعاملات اليومية', 'Same-day recorded / total transactions', 'daily', 1.0, 0.2, 'scored', NULL),
  ('FIN-ACC-02', 'Invoice Processing Time', 'وقت معالجة الفاتورة', 'Avg hours transaction to invoice issued', 'monthly', 24.0, 0.2, 'scored', (select id from def.key_results where code='CO4.KR4')),
  ('FIN-ACC-03', 'Data Entry Error Rate', 'معدل أخطاء إدخال البيانات', 'Entries with errors / total (audit sample)', 'monthly', 0.02, 0.2, 'scored', NULL),
  ('FIN-ACC-04', 'Receipt & Document Filing', 'أرشفة الإيصالات والمستندات', 'On-time filed / total documents', 'daily', 1.0, 0.2, 'scored', NULL),
  ('FIN-ACC-05', 'Dispute Financial Support', 'الدعم المالي للنزاعات', 'Avg days to deliver dispute package', 'monthly', 2.0, 0.2, 'scored', NULL),
  ('HR-01', 'Fawry Payroll System Accuracy', 'دقة نظام فوري للرواتب', 'Error-free entries / total payroll entries', 'monthly', 0.99, 0.2, 'scored', NULL),
  ('HR-02', 'Employee Document Completeness', 'اكتمال ملفات الموظفين', 'Complete files / total employee files', 'quarterly', 1.0, 0.15, 'scored', NULL),
  ('HR-03', 'New Hire Onboarding Checklist', 'قائمة تأهيل الموظف الجديد', 'On-time items / total checklist items', 'monthly', 1.0, 0.2, 'scored', NULL),
  ('HR-04', 'Attendance Record Accuracy', 'دقة سجلات الحضور', 'Matching records / total checked', 'monthly', 0.99, 0.15, 'scored', NULL),
  ('HR-05', 'Leave Request Processing Time', 'وقت معالجة طلبات الإجازة', 'Avg business days request to processed', 'monthly', 1.0, 0.15, 'scored', NULL),
  ('HR-06', 'Monthly HR Report Delivery', 'تسليم تقرير الموارد البشرية الشهري', 'On-time delivery (yes/no)', 'monthly', 3.0, 0.15, 'scored', NULL),
  ('HR-BC-01', 'Attendance Rate', 'معدل الحضور', 'Days present / scheduled working days', 'monthly', 0.95, 0.35, 'scored', NULL),
  ('HR-BC-02', 'Office Readiness', 'جاهزية المكتب', 'Readiness checks passed / total working days', 'daily', 8.0, 0.35, 'scored', NULL),
  ('HR-BC-03', 'Supply Inventory Management', 'إدارة مخزون المستلزمات', 'Stockout incidents per month', 'monthly', NULL, 0.3, 'scored', NULL);
